### ISSUE TITLE
template not compatible

### ISSUE THREAD

**Issue by psarrea** [lddweb/ldd-directory-lite#94]
i just finish to install the plugin . Is great but is not clean why my theme wp. I'm not a "pro" and i dont know how to adapt it. i can use it finaly. Someon can help ? 
regards
![capture d ecran 2017-11-28 a 21 51 13](https://user-images.githubusercontent.com/34075509/33343618-4a0f96ee-d486-11e7-83d5-4f5eaf525664.png)

**Comment by ohaw87** [comment]
I have the very same problem. this is a subpage, and it is just too wide. any advice is most welcome as I would hate to find another plugin while this one is just great!

**Comment by LDDConsulting** [comment]
You can override template files in your theme if there any layout issues.

  | The LDD Directory Lite template files which are  responsible for the markup and structure for the frontend of your  directory are located here:              /ldd-directory-lite/templates/                            In order to modify the look and feel of your directory,  you will need to copy the specific file(s) to a folder in your theme  called lddlite_templates
